language: node_js
env:
- CXX=g++-4.8
node_js:
- '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: false
before_install:
- "$CXX --version"
deploy:

  provider: releases
    user: "GITHUB USERNAME"
    password: "GITHUB PASSWORD"
    file: "$TRAVIS_BUILD_DIR/lib/binding/bcrypt_lib.node"
    skip_cleanup: true
  on:
    tags: false
    repo: jungule/node.bcrypt.js
