language: node_js
env:
  matrix:
  - CXX=g++-4.8
  global:
node_js:
- '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: false
before_install:
- "$CXX --version"
deploy:
  provider: releases
  api_key:
    secure: TyC++r5iQD9AF+L0RaHsqNS5J5T0Ek0D2qoQOOkrzOG4w54jWkmT/+gK4eZGRA1y0adayyvdQTAI1Q4PeA6ZfIAJ3sW3E+iYTSvk1fH8mQ9HAhcm2Rd5D4HUectw1EZNt3nhmMxPgpdsn47RfsfwcJ77TCZS9IQ9iWTTe2yZRLQqiYtUmUrI7mdgJzXkhwq8376aC3j3UB9aMrn9Rmtf/QfaGfCXqbYvkLE57Qlr9i55/tirU8DE4bTOI0DUNGCfDJILTIcvPX+2ZuN3G14w783pcwSUTW/6HBoKftLUXgx5RacFzlJXaRDRfXY+iAoklIKnFZ2I+W1rZFATMSnZkPP397z2PF0Yb6P0hW+eAPjr+KmzVSfgabdQnCWdqR5xw1vzRAj9iL1QMQjsjwOV3FxdqfJVbSz6yrD8Qf+6j9Utv+yXatObtpnyRs7boAaM07H9rtVrzfdf3b4AzO+v4UH8clj6tLP/tn2Ter4WIgjCOw7HyREhVCcQgxSDGAlqu81rDzgJdn27M1P+zoLCMlonJINbQajZvl+dNfwGaLjFLY3gFmQNC8VAWYOQfsLJu/+9V6BqUJJmeYnT7UZPpq6bdg/ud/5PhdcelAvo9zt93ZVheI2fTyLsHcE+JsqYFu4hFaiKgcknt6kI8VtiIRMMVbnDaASLRfnJEkHy3QE=
  file: "$TRAVIS_BUILD_DIR/lib/binding/bcrypt_lib.node"
  skip_cleanup: true
  on:
    tags: false
    repo: jungule/node.bcrypt.js
