language: node_js
env:
- CXX=g++-4.8
node_js:
- '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: false
before_install:
- "$CXX --version"
deploy:
  provider: releases
  api_key:
    secure: VBQHF/pHNrbIukh+FsiFmQotkhLlak4qGC/mGFsy/L26a8Q2CT+8n3+7N/JQup46eJpqt4vSjaFLQSbfn5nt6BSj+NEMB8IQxtjd+LNEUveDKxIRuNPln6yZsUrtNgSeU0BZzCu/QtpODk6JrTf/VJzc8//yMhQrIUERMIYItiDIpkhasigTyB9m8nHIRwzNFZV1iFX7zk2VtCCzXIVpJIXOA98qlHIajq6UHHnAfx6s4olILkqSK1l69tZmd+egZxbWxgF7bR5KDjIRf81Bz8Kg8JusVMRboubGIaCneOC3PaRQtlV4vwJnAuxI8Joi+ni/5lwazxOn1cMHVfz3DH7ejguivPG9nxSU6WNajCIp03R1/ZHLDn/r0wLZ5AJQYmPOyytU2TNHk9EzF6u7AaGRH8OdeU15BZdWgzkk8z7DHovG7BADG89sGYftWDwJeKYDMTpqeCRo1ghPbRFjzqbq8ymeeYh9snhNDRVyNPqqzSZHNwv8kmND8sznxqy+vJUGrelrr32IrblBGbfL6NmfimAQrdjuZFxehXTGdGmeVPq/1RINffj87SKh5wbjiHt5hsuN9Ofa2A7fcgiDcgKz/ThEFnTRPIQFLkuQfW00Z2ZVk4aeIDvPrffJcPe+vXZIMT6ve5MNtToco3Z3rcAmZsuUFhpVuO2fOKLZMPo=
    file: '$TRAVIS_BUILD_DIR/lib/binding/bcrypt_lib.node'
  on:
    tags: false
    repo: jungule/node.bcrypt.js
